# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d707af7aab0242f960d3625954d1ed45f4f9038a16b3a29ca0c2ae27ffa3ed4323059ced007de48b6e249332e6b1e8ee6b2f77c1997b482d3d8ff9d339471cd1

test:
  secret_key_base: 201b8f7610cf275306a4e1f83899967ca6af7fedf49168d02d67b49210c7dbffce271fd300b89eaba24c1dc3c9def20b9a5ebc88a69a92c9c2199af6024ff1be

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
